name: Build OpenWrt for Xiaomi Mi Router 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python3 unzip wget zlib1g-dev python3-distutils

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy custom config
      run: |
        cp $GITHUB_WORKSPACE/mir3.config openwrt/.config

    - name: Build firmware
      run: |
        cd openwrt
        make defconfig
        make download -j8
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: Xiaomi-Mi-R3-Firmware
        path: openwrt/bin/targets/ramips/mt7620/
