name: Build OpenWrt Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OpenWrt environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git unzip \
              libncurses5-dev zlib1g-dev gawk flex wget \
              gettext libssl-dev xsltproc file libcurl4-openssl-dev

      - name: Prepare OpenWrt build
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Build OpenWrt firmware
        run: |
          make -j$(nproc)

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: bin/
