name: OpenWrt Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OpenWrt feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy custom config
        run: |
          cp ./config/r3.config .config
          make defconfig

      - name: Build OpenWrt firmware
        run: |
          make -j$(nproc) V=s

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: bin/targets/ramips/mt7621/*.bin
