name: Build OpenWrt Firmware

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential ccache libncurses5-dev gawk gettext unzip file python3 python3-distutils python3-setuptools python3-pip git

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy custom config file
        run: cp config/r3.config .config

      - name: Synchronize config (defconfig)
        run: make defconfig

      - name: Build OpenWrt firmware
        run: make -j$(nproc) V=s

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-firmware
          path: bin/targets/ramips/mt76x8/
